/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalmetodos;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Morales
 */
public class MNM_Panel extends javax.swing.JPanel {

    Validate V = new Validate();
    Mensaje M = new Mensaje();
    
    public MNM_Panel(JButton backButton, int x_button, int y_button, JLabel Titulo) {
        initComponents();
        int titulo_x = 586;
        int titulo_y = 80;
        this.add(backButton);
        backButton.setBounds(x_button, y_button, 50, 50);
        this.add(Titulo);
        //Titulo.setBounds((this.WIDTH-titulo_x)/2, (y_button-(titulo_y/2)), titulo_x, titulo_y);
        
        Titulo.setBounds(200, Math.abs(y_button - (titulo_y/2)), titulo_x, titulo_y);
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        MNM_x = new javax.swing.JTextField();
        MNM_Fx1 = new javax.swing.JTextField();
        MNM_Calculate = new javax.swing.JButton();
        SeccionResultados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MNM_Result = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        MNM_Fx2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MNM_y = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 219, 255), 4));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Primera ecuación:");

        MNM_x.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MNM_x.setToolTipText("Valor númerico a evaluar");

        MNM_Fx1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MNM_Fx1.setToolTipText("Ecuación a evaluar con formato x^n+x^n-1+... (ej. 3x^2-8x-1)");

        MNM_Calculate.setText("Calcular");
        MNM_Calculate.setToolTipText("Calcular");
        MNM_Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNM_CalculateActionPerformed(evt);
            }
        });

        SeccionResultados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(185, 219, 255), 1, true));

        MNM_Result.setEditable(false);
        MNM_Result.setColumns(20);
        MNM_Result.setRows(5);
        MNM_Result.setToolTipText("Conclusión de operación");
        jScrollPane1.setViewportView(MNM_Result);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel9.setText("Resultados:");

        javax.swing.GroupLayout SeccionResultadosLayout = new javax.swing.GroupLayout(SeccionResultados);
        SeccionResultados.setLayout(SeccionResultadosLayout);
        SeccionResultadosLayout.setHorizontalGroup(
            SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeccionResultadosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        SeccionResultadosLayout.setVerticalGroup(
            SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeccionResultadosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        MNM_Fx2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MNM_Fx2.setToolTipText("Ecuación a evaluar con formato x^n+x^n-1+... (ej. 3x^2-8x-1)");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(185, 219, 255));
        jLabel5.setText("y =");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Segunda ecuación:");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(185, 219, 255));
        jLabel6.setText("y =");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Empezando con:");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(185, 219, 255));
        jLabel8.setText("x = ");

        MNM_y.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MNM_y.setToolTipText("Valor númerico a evaluar");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(185, 219, 255));
        jLabel10.setText("y = ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeccionResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MNM_x, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MNM_y, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(155, 155, 155))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(MNM_Calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MNM_Fx1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(MNM_Fx2))))
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(MNM_Fx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(MNM_Fx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(MNM_Calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MNM_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(MNM_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(SeccionResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MNM_CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNM_CalculateActionPerformed
        try{
        String Fx1 = MNM_Fx1.getText();
        String Fx2 = MNM_Fx2.getText();
        ArrayList check_Fx1 = V.isEquationValid(Fx1);
        if((boolean) check_Fx1.get(0)){
            ArrayList check_Fx2 = V.isEquationValid(Fx2);
            if((boolean) check_Fx2.get(0)){
                if(V.isNumberValid(MNM_x.getText())){
                    if(V.isNumberValid(MNM_y.getText())){
                        MNM mnm = new MNM(new PolyEquation((List<String>) check_Fx1.get(2)), new PolyEquation((List<String>) check_Fx2.get(2)), Double.parseDouble(MNM_x.getText()), Double.parseDouble(MNM_y.getText()));
                        ArrayList results = mnm.start();
                        if((boolean) results.get(0)){
                            String final_res = "Las funciones se intersectan en ("+(double) results.get(2)+", "+(double) results.get(3)+").";
                            MNM_Result.setText(final_res);
                            return;
                        }
                        else{
                            M.mostarAdver((String) results.get(1));
                        }
                    }
                    else{
                        M.mostarError("El valor de y no es válido.");
                    }
                }
                else{
                    M.mostarError("El valor de x no es válido.");
                }
            }
            else{
                M.mostarError("Segunda ecuación: "+ (String) check_Fx2.get(1));
            }            
        }
        else{
            M.mostarError("Primera ecuación: "+ (String) check_Fx1.get(1));
        }
        MNM_Result.setText("");
        }
        catch(Exception e){
            M.mostarError("ERROR FATAL: "+e.toString()+"\nCERRANDO PROGRAMA.");
            System.exit(0);
        }
    }//GEN-LAST:event_MNM_CalculateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MNM_Calculate;
    private javax.swing.JTextField MNM_Fx1;
    private javax.swing.JTextField MNM_Fx2;
    private javax.swing.JTextArea MNM_Result;
    private javax.swing.JTextField MNM_x;
    private javax.swing.JTextField MNM_y;
    private javax.swing.JPanel SeccionResultados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
