/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalmetodos;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Morales
 */
public class MRPMC_Panel extends javax.swing.JPanel {

    Validate V = new Validate();
    Mensaje M = new Mensaje();
    private final int TABLE_HEIGHT = 333;
    private final int SMALL_FONT_SIZE = 10;
    
    
    public MRPMC_Panel(JButton backButton, int x_button, int y_button, JLabel Titulo) {
        initComponents();
        int titulo_x = 586;
        int titulo_y = 80;
        this.add(backButton);
        backButton.setBounds(x_button, y_button, 50, 50);
        this.add(Titulo); 
        Titulo.setBounds(200, Math.abs(y_button - (titulo_y/2)), titulo_x, titulo_y);
        this.validate();
        
        //Inicializar componentes
        MRPMC_Points.setEditor(new JSpinner.DefaultEditor(MRPMC_Points));
        MRPMC_Degree.setEditor(new JSpinner.DefaultEditor(MRPMC_Degree));
        
        jScrollPane1.setVerticalScrollBarPolicy(jScrollPane1.VERTICAL_SCROLLBAR_NEVER);
        
        MRPMC_xy_Values.setTableHeader(null);      
        
        changeTable(MRPMC_xy_Values, (int)MRPMC_Points.getValue(), 2);
        //setM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MRPMC_xy_Values = new javax.swing.JTable();
        MGJ_ResolveButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MRPMC_Degree = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        MRPMC_r2_Output = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MRPMC_Px_Output = new javax.swing.JTextArea();
        MRPMC_Points = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 219, 255), 4));
        setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(185, 219, 255));
        jLabel1.setText("x");

        MRPMC_xy_Values.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        MRPMC_xy_Values.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        MRPMC_xy_Values.setGridColor(new java.awt.Color(204, 204, 204));
        MRPMC_xy_Values.setRowSelectionAllowed(false);
        MRPMC_xy_Values.setShowGrid(true);
        MRPMC_xy_Values.getTableHeader().setResizingAllowed(false);
        MRPMC_xy_Values.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(MRPMC_xy_Values);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

        MGJ_ResolveButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        MGJ_ResolveButton.setText("Ajustar");
        MGJ_ResolveButton.setToolTipText("Iniciar el ajuste de curva");
        MGJ_ResolveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MGJ_ResolveButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(185, 219, 255));
        jLabel6.setText("y");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Cantidad de puntos:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Grado:");

        MRPMC_Degree.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1, 1));
        MRPMC_Degree.setToolTipText("Grado máximo de la ecuación resultante");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 219, 255)));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("Resultados");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("P(x) =");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("r² =");

        MRPMC_r2_Output.setEditable(false);
        MRPMC_r2_Output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MRPMC_r2_Output.setToolTipText("Correlación r^2");
        MRPMC_r2_Output.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        MRPMC_Px_Output.setEditable(false);
        MRPMC_Px_Output.setColumns(20);
        MRPMC_Px_Output.setRows(5);
        MRPMC_Px_Output.setToolTipText("Ecuación resultante de curva");
        MRPMC_Px_Output.setAutoscrolls(false);
        jScrollPane1.setViewportView(MRPMC_Px_Output);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MRPMC_r2_Output, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(MRPMC_r2_Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        MRPMC_Points.setModel(new javax.swing.SpinnerNumberModel(2, 2, 20, 1));
        MRPMC_Points.setToolTipText("Cantidad de puntos en x,y");
        MRPMC_Points.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MRPMC_PointsStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(185, 219, 255));
        jLabel9.setText("= n");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(185, 219, 255));
        jLabel11.setText("= m");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MRPMC_Points, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MRPMC_Degree, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(39, 39, 39)
                                .addComponent(MGJ_ResolveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MGJ_ResolveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MRPMC_Points, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(MRPMC_Degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MRPMC_PointsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MRPMC_PointsStateChanged
        changeTable(MRPMC_xy_Values, (int)MRPMC_Points.getValue(), 2);
        setM();
        clear();
    }//GEN-LAST:event_MRPMC_PointsStateChanged

    private void MGJ_ResolveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MGJ_ResolveButtonActionPerformed
        try{
        if((int)MRPMC_Degree.getValue()>=(int) MRPMC_Points.getValue()||(int)MRPMC_Degree.getValue()==0){
            M.mostarError("El grado de la curva no puede ser\n"
                        + "mayor o igual al número de puntos");
            clear();
            return;
        }
        if(!V.isMatrixValid(getXYValues())){
            M.mostarError("Alguno de los valores x o y no es válido.");
            clear();
            return;
        }
        if(!checkXValues(getXYValues())){
            M.mostarError("Los valores de x no pueden repetirse.");
            clear();
            return;
        }
        MRPMC mrpmc = new MRPMC(new Matrix(getXYValues()), (int)MRPMC_Degree.getValue());
        ArrayList results = mrpmc.start();
        MRPMC_Px_Output.setText((String)results.get(0));
        MRPMC_r2_Output.setText(""+(double)results.get(1));
        }
        catch(Exception e){
            M.mostarError("ERROR FATAL: "+e.toString()+"\nCERRANDO PROGRAMA.");
            System.exit(0);
        }
    }//GEN-LAST:event_MGJ_ResolveButtonActionPerformed

    private void changeTable(JTable table, int rows, int columns){        
        DefaultTableModel temp = new DefaultTableModel();
        temp.setColumnCount(columns);
        temp.setRowCount(rows);
        table.setModel(temp);
        table.setRowHeight((TABLE_HEIGHT/(int)MRPMC_Points.getValue())+((int)MRPMC_Points.getValue()>15? 1 : 0));
        Font table_font = table.getFont();
        int font_size = (int) ((TABLE_HEIGHT/(int)MRPMC_Points.getValue()) * 0.33);
        if (font_size < 11) {
            font_size = SMALL_FONT_SIZE;
        }
        Font new_font = new Font(table_font.getName(), table_font.getStyle(), font_size);
        table.setFont(new_font);      
    }
   
    private String[][] getXYValues(){
        String Values[][] = new String[MRPMC_xy_Values.getRowCount()][MRPMC_xy_Values.getColumnCount()];
        for(int i = 0; i<MRPMC_xy_Values.getRowCount(); i++){
            for(int j = 0; j<MRPMC_xy_Values.getColumnCount(); j++){
                String n = (String)MRPMC_xy_Values.getModel().getValueAt(i, j);
                Values[i][j] = (n==null?"":n);
            }           
        }
        return Values;
    }
    
    private boolean checkXValues(String[][] values){
        for(int i = 0; i<MRPMC_xy_Values.getRowCount(); i++){
            for(int j = 0; j<MRPMC_xy_Values.getRowCount(); j++){
                String n = (String)MRPMC_xy_Values.getModel().getValueAt(i, 0);
                String m = (String)MRPMC_xy_Values.getModel().getValueAt(j, 0);
                if(n.equals(m)&&i!=j){
                    return false;
                }
            }           
        }
        return true;
    }
    
    private void setM(){
        int n = (int) MRPMC_Points.getValue();
        SpinnerNumberModel new_model = new SpinnerNumberModel();
        new_model.setMaximum(n-1);
        new_model.setMinimum(1);
        new_model.setStepSize(1);
        MRPMC_Degree.setModel(new_model);
        MRPMC_Degree.setValue(1);
    }
    
    private void clear(){
        MRPMC_Px_Output.setText("");
        MRPMC_r2_Output.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MGJ_ResolveButton;
    private javax.swing.JSpinner MRPMC_Degree;
    private javax.swing.JSpinner MRPMC_Points;
    private javax.swing.JTextArea MRPMC_Px_Output;
    private javax.swing.JTextField MRPMC_r2_Output;
    private javax.swing.JTable MRPMC_xy_Values;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
