/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalmetodos;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Morales
 */
public class MTH_Panel extends javax.swing.JPanel {

    Validate V = new Validate();
    Mensaje M = new Mensaje();
    
    public MTH_Panel(JButton backButton, int x_button, int y_button, JLabel Titulo) {
        initComponents();
        int titulo_x = 586;
        int titulo_y = 80;
        this.add(backButton);
        backButton.setBounds(x_button, y_button, 50, 50);
        this.add(Titulo);
        //Titulo.setBounds((this.WIDTH-titulo_x)/2, (y_button-(titulo_y/2)), titulo_x, titulo_y);
        
        Titulo.setBounds(200, Math.abs(y_button - (titulo_y/2)), titulo_x, titulo_y);
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        MTH_x_Input = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MTH_Fx_Input = new javax.swing.JTextField();
        MTHCalculate_Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SeccionResultados = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        MTH_Fx_Output = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        MTH_F1x_Output = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        MTH_F2x_Output = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MTH_C_Output = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 219, 255), 4));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Evaluar");

        MTH_x_Input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MTH_x_Input.setToolTipText("Valor númerico a evaluar");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("en");

        MTH_Fx_Input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MTH_Fx_Input.setToolTipText("Ecuación a evaluar con formato x^n+x^n-1+... (ej. 3x^2-8x-1)");

        MTHCalculate_Button.setText("Calcular");
        MTHCalculate_Button.setToolTipText("Calcular");
        MTHCalculate_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTHCalculate_ButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(185, 219, 255));
        jLabel3.setText("x =");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(185, 219, 255));
        jLabel4.setText("F(x) =");

        SeccionResultados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(185, 219, 255), 1, true));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("Resultados:");

        MTH_Fx_Output.setEditable(false);
        MTH_Fx_Output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MTH_Fx_Output.setToolTipText("Resultado de F(x)");
        MTH_Fx_Output.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MTH_Fx_OutputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MTH_Fx_OutputFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("F(x) =");

        MTH_F1x_Output.setEditable(false);
        MTH_F1x_Output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MTH_F1x_Output.setToolTipText("Resultado de F'(x)");
        MTH_F1x_Output.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MTH_F1x_OutputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MTH_F1x_OutputFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("F'(x) =");

        MTH_F2x_Output.setEditable(false);
        MTH_F2x_Output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MTH_F2x_Output.setToolTipText("Resultado de F''(x)");
        MTH_F2x_Output.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MTH_F2x_OutputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MTH_F2x_OutputFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("F''(x) =");

        MTH_C_Output.setEditable(false);
        MTH_C_Output.setColumns(20);
        MTH_C_Output.setRows(5);
        MTH_C_Output.setToolTipText("Conclusión de operación");
        jScrollPane1.setViewportView(MTH_C_Output);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Conclusión:");

        javax.swing.GroupLayout SeccionResultadosLayout = new javax.swing.GroupLayout(SeccionResultados);
        SeccionResultados.setLayout(SeccionResultadosLayout);
        SeccionResultadosLayout.setHorizontalGroup(
            SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeccionResultadosLayout.createSequentialGroup()
                .addGroup(SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SeccionResultadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MTH_F2x_Output, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SeccionResultadosLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SeccionResultadosLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(206, 206, 206))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SeccionResultadosLayout.createSequentialGroup()
                                .addGroup(SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MTH_F1x_Output, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                    .addComponent(MTH_Fx_Output))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(22, 22, 22))
        );
        SeccionResultadosLayout.setVerticalGroup(
            SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeccionResultadosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeccionResultadosLayout.createSequentialGroup()
                        .addGroup(SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(MTH_Fx_Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(MTH_F1x_Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SeccionResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(MTH_F2x_Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3)
                                .addGap(5, 5, 5)
                                .addComponent(MTH_x_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10)
                                .addComponent(MTH_Fx_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SeccionResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(MTHCalculate_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MTH_x_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(MTH_Fx_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MTHCalculate_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeccionResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MTHCalculate_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTHCalculate_ButtonActionPerformed
        try{
        String x = MTH_x_Input.getText();
        String Fx = MTH_Fx_Input.getText();
        ArrayList results = V.isEquationValid(Fx);
        if((boolean) results.get(0)){
            if(V.isNumberValid(x)){
                PolyEquation Equation = new PolyEquation((List<String>) results.get(2));                
                MTH mth = new MTH(Equation, Double.parseDouble(x)); 
                ArrayList start = mth.start();
                MTH_Fx_Output.setText(""+(double) start.get(0));
                MTH_F1x_Output.setText(""+(double) start.get(1));
                MTH_F2x_Output.setText(""+(double) start.get(2));
                MTH_C_Output.setText((String)start.get(4));
                return;
            }
            else{
                M.mostarError("El número no es válido.");
            }
        }
        else{
            M.mostarError((String) results.get(1));
        }
        clear();
        }
        catch(Exception e){
            M.mostarError("ERROR FATAL: "+e.toString()+"\nCERRANDO PROGRAMA.");
            System.exit(0);
        }
    }//GEN-LAST:event_MTHCalculate_ButtonActionPerformed

    private void MTH_Fx_OutputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MTH_Fx_OutputFocusGained
        //NO PONER NADA
    }//GEN-LAST:event_MTH_Fx_OutputFocusGained

    private void MTH_Fx_OutputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MTH_Fx_OutputFocusLost
        //NO PONER NADA
    }//GEN-LAST:event_MTH_Fx_OutputFocusLost

    private void MTH_F1x_OutputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MTH_F1x_OutputFocusGained
        //NO PONER NADA 
    }//GEN-LAST:event_MTH_F1x_OutputFocusGained

    private void MTH_F1x_OutputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MTH_F1x_OutputFocusLost
        //NO PONER NADA 
    }//GEN-LAST:event_MTH_F1x_OutputFocusLost

    private void MTH_F2x_OutputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MTH_F2x_OutputFocusGained
        //NO PONER NADA 
    }//GEN-LAST:event_MTH_F2x_OutputFocusGained

    private void MTH_F2x_OutputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MTH_F2x_OutputFocusLost
        //NO PONER NADA 
    }//GEN-LAST:event_MTH_F2x_OutputFocusLost

    private void clear(){
        MTH_F1x_Output.setText("");
        MTH_F2x_Output.setText("");
        MTH_C_Output.setText("");
        MTH_Fx_Output.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MTHCalculate_Button;
    private javax.swing.JTextArea MTH_C_Output;
    private javax.swing.JTextField MTH_F1x_Output;
    private javax.swing.JTextField MTH_F2x_Output;
    private javax.swing.JTextField MTH_Fx_Input;
    private javax.swing.JTextField MTH_Fx_Output;
    private javax.swing.JTextField MTH_x_Input;
    private javax.swing.JPanel SeccionResultados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
