/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalmetodos;

import java.awt.Component;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.font.TextAttribute;
import java.util.Map;

/**
 *
 * @author Morales
 */
public class Window extends javax.swing.JFrame {

    private final int XAXIS_BACKBUTTON_POSITION = 90;
    private final int YAXIS_BACKBUTTON_POSITION = 30;
    
    private String CURRENT_METHOD;
    private final String TITLE_CODE = "{-Main-}";
    private String TITLE_TAG = "<html><center>"+ "{-Main-}" +"</center></html>";
    
    public final String MTH_Title = "Método de Horner";
    public final String MNR_Title = "Método de Newton-Rhapson";
    public final String OPM_Title = "Operaciones con matrices";
    public final String OPM_1_Title = "una sola matriz";
    public final String OPM_2_Title = "dos matrices";
    public final String MGJ_Title = "Método de Gauss-Jordan";
    public final String MNM_Title = "Método de Newton Multivariable";
    public final String MRPMC_Title = "Método de Regresión Polinomial por Mínimos Cuadrados";
    
    public final String MTH_CODE = "MTH";
    public final String MNR_CODE = "MNR";
    public final String OPM_CODE = "OPM";
    public final String OPM_1_CODE = "OPM_1";
    public final String OPM_2_CODE = "OPM_2";
    public final String MGJ_CODE = "MGJ";
    public final String MNM_CODE = "MNM";
    public final String MRPMC_CODE = "MRPMC";
    
    //Objetos compartidos
    public Mensaje M = new Mensaje();
    public Validate V = new Validate();
    
    public Window() {
        CURRENT_METHOD = TITLE_CODE;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        Stage.removeAll();
        Stage.setLayout(new GridLayout(1,1));
        Stage.add(PantallaPrincipal);
        
        MTH_Button.setText(MTH_Title);
        MNR_Button.setText(MNR_Title);
        OPM_Button.setText(OPM_Title);
        OPM_1_Button.setText(OPM_1_Title);
        OPM_2_Button.setText(OPM_2_Title);
        MGJ_Button.setText(MGJ_Title);
        MNM_Button.setText(MNM_Title);
        MRPMC_Button.setText(MRPMC_Title);
        
        MTH_Button.setToolTipText(MTH_Title);
        MNR_Button.setToolTipText(MNR_Title);
        OPM_Button.setToolTipText(OPM_Title);
        OPM_1_Button.setToolTipText(OPM_Title+": "+OPM_1_Title);
        OPM_2_Button.setToolTipText(OPM_Title+": "+OPM_2_Title);
        MGJ_Button.setToolTipText(MGJ_Title);
        MNM_Button.setToolTipText(MNM_Title);
        MRPMC_Button.setToolTipText(MRPMC_Title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainBack_Button = new javax.swing.JButton();
        MethodTitle_Label = new javax.swing.JLabel();
        Stage = new javax.swing.JPanel();
        PantallaPrincipal = new javax.swing.JPanel();
        ButtonSection = new javax.swing.JPanel();
        MTH_Button = new javax.swing.JButton();
        MNR_Button = new javax.swing.JButton();
        MGJ_Button = new javax.swing.JButton();
        MNM_Button = new javax.swing.JButton();
        MRPMC_Button = new javax.swing.JButton();
        OPM_Section = new javax.swing.JLayeredPane();
        OPM_MainButtonSection = new javax.swing.JPanel();
        OPM_Button = new javax.swing.JButton();
        OPM_ChooseSection = new javax.swing.JPanel();
        OPM_1_Button = new javax.swing.JButton();
        OPM_2_Button = new javax.swing.JButton();
        BacktoOPMSection_Button = new javax.swing.JButton();
        ButtonSectionTitle = new javax.swing.JLabel();
        TopBar = new javax.swing.JPanel();
        MainTitle = new javax.swing.JLabel();
        TeamTitle = new javax.swing.JLabel();

        MainBack_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        MainBack_Button.setToolTipText("Ir a pantalla principal");
        MainBack_Button.setBorder(null);
        MainBack_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainBack_ButtonActionPerformed(evt);
            }
        });

        MethodTitle_Label.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        MethodTitle_Label.setForeground(new java.awt.Color(31, 46, 75));
        MethodTitle_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MethodTitle_Label.setText("Method");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Final");
        setBackground(new java.awt.Color(185, 219, 255));

        PantallaPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 219, 255), 4));

        MTH_Button.setForeground(new java.awt.Color(31, 46, 75));
        MTH_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MTH.png"))); // NOI18N
        MTH_Button.setText("jButton1");
        MTH_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MTH_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MTH_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTH_ButtonActionPerformed(evt);
            }
        });

        MNR_Button.setForeground(new java.awt.Color(31, 46, 75));
        MNR_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MNR.png"))); // NOI18N
        MNR_Button.setText("jButton1");
        MNR_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MNR_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MNR_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNR_ButtonActionPerformed(evt);
            }
        });

        MGJ_Button.setForeground(new java.awt.Color(31, 46, 75));
        MGJ_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MGJ.png"))); // NOI18N
        MGJ_Button.setText("jButton1");
        MGJ_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MGJ_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MGJ_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MGJ_ButtonActionPerformed(evt);
            }
        });

        MNM_Button.setForeground(new java.awt.Color(31, 46, 75));
        MNM_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MNM.png"))); // NOI18N
        MNM_Button.setText("jButton1");
        MNM_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MNM_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MNM_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNM_ButtonActionPerformed(evt);
            }
        });

        MRPMC_Button.setForeground(new java.awt.Color(31, 46, 75));
        MRPMC_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MRPMC.png"))); // NOI18N
        MRPMC_Button.setText("jButton1");
        MRPMC_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MRPMC_Button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        MRPMC_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MRPMC_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRPMC_ButtonActionPerformed(evt);
            }
        });

        OPM_Button.setForeground(new java.awt.Color(31, 46, 75));
        OPM_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OPM.png"))); // NOI18N
        OPM_Button.setText("jButton1");
        OPM_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OPM_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OPM_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPM_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OPM_MainButtonSectionLayout = new javax.swing.GroupLayout(OPM_MainButtonSection);
        OPM_MainButtonSection.setLayout(OPM_MainButtonSectionLayout);
        OPM_MainButtonSectionLayout.setHorizontalGroup(
            OPM_MainButtonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OPM_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );
        OPM_MainButtonSectionLayout.setVerticalGroup(
            OPM_MainButtonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OPM_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        OPM_1_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OPM_1.png"))); // NOI18N
        OPM_1_Button.setText("jButton1");
        OPM_1_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OPM_1_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OPM_1_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPM_1_ButtonActionPerformed(evt);
            }
        });

        OPM_2_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OPM_2.png"))); // NOI18N
        OPM_2_Button.setText("jButton2");
        OPM_2_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OPM_2_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OPM_2_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPM_2_ButtonActionPerformed(evt);
            }
        });

        BacktoOPMSection_Button.setText("Esconder");
        BacktoOPMSection_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoOPMSection_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OPM_ChooseSectionLayout = new javax.swing.GroupLayout(OPM_ChooseSection);
        OPM_ChooseSection.setLayout(OPM_ChooseSectionLayout);
        OPM_ChooseSectionLayout.setHorizontalGroup(
            OPM_ChooseSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OPM_ChooseSectionLayout.createSequentialGroup()
                .addComponent(OPM_1_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OPM_2_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(BacktoOPMSection_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OPM_ChooseSectionLayout.setVerticalGroup(
            OPM_ChooseSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OPM_ChooseSectionLayout.createSequentialGroup()
                .addComponent(BacktoOPMSection_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OPM_ChooseSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OPM_2_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(OPM_1_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout OPM_SectionLayout = new javax.swing.GroupLayout(OPM_Section);
        OPM_Section.setLayout(OPM_SectionLayout);
        OPM_SectionLayout.setHorizontalGroup(
            OPM_SectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OPM_MainButtonSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(OPM_SectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(OPM_ChooseSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OPM_SectionLayout.setVerticalGroup(
            OPM_SectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OPM_MainButtonSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(OPM_SectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(OPM_ChooseSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OPM_Section.setLayer(OPM_MainButtonSection, javax.swing.JLayeredPane.DEFAULT_LAYER);
        OPM_Section.setLayer(OPM_ChooseSection, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ButtonSectionLayout = new javax.swing.GroupLayout(ButtonSection);
        ButtonSection.setLayout(ButtonSectionLayout);
        ButtonSectionLayout.setHorizontalGroup(
            ButtonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonSectionLayout.createSequentialGroup()
                .addGroup(ButtonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonSectionLayout.createSequentialGroup()
                        .addComponent(MTH_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MNR_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OPM_Section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ButtonSectionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MGJ_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MNM_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MRPMC_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ButtonSectionLayout.setVerticalGroup(
            ButtonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OPM_Section)
                    .addGroup(ButtonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(MNR_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MTH_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonSectionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ButtonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MNM_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MGJ_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(MRPMC_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        ButtonSectionTitle.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        ButtonSectionTitle.setText(" Escoge el método que deseas usar:");

        javax.swing.GroupLayout PantallaPrincipalLayout = new javax.swing.GroupLayout(PantallaPrincipal);
        PantallaPrincipal.setLayout(PantallaPrincipalLayout);
        PantallaPrincipalLayout.setHorizontalGroup(
            PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonSectionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PantallaPrincipalLayout.setVerticalGroup(
            PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonSectionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout StageLayout = new javax.swing.GroupLayout(Stage);
        Stage.setLayout(StageLayout);
        StageLayout.setHorizontalGroup(
            StageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        StageLayout.setVerticalGroup(
            StageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TopBar.setBackground(new java.awt.Color(185, 219, 255));
        TopBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 219, 255)));

        MainTitle.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        MainTitle.setForeground(new java.awt.Color(31, 46, 75));
        MainTitle.setText("Proyecto Final");

        TeamTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        TeamTitle.setForeground(new java.awt.Color(255, 255, 255));
        TeamTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TeamTitle.setText("<html><u>Los Inges</u></html>");
        TeamTitle.setToolTipText("Ver equipo");
        TeamTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TeamTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeamTitleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TeamTitleMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
        TopBar.setLayout(TopBarLayout);
        TopBarLayout.setHorizontalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(MainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TeamTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        TopBarLayout.setVerticalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeamTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(MainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Stage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OPM_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPM_ButtonActionPerformed
        OPM_MainButtonSection.setVisible(false);
        OPM_ChooseSection.setVisible(true);
    }//GEN-LAST:event_OPM_ButtonActionPerformed

    private void MGJ_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MGJ_ButtonActionPerformed
        CURRENT_METHOD = MGJ_Title;
        MethodTitle_Label.setText(TITLE_TAG.replace(TITLE_CODE, CURRENT_METHOD));
        setScreen(new MGJ_Panel(MainBack_Button, XAXIS_BACKBUTTON_POSITION, YAXIS_BACKBUTTON_POSITION, MethodTitle_Label));
    }//GEN-LAST:event_MGJ_ButtonActionPerformed

    private void BacktoOPMSection_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoOPMSection_ButtonActionPerformed
        OPM_MainButtonSection.setVisible(true);
        OPM_ChooseSection.setVisible(false);
    }//GEN-LAST:event_BacktoOPMSection_ButtonActionPerformed

    private void MTH_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTH_ButtonActionPerformed
        CURRENT_METHOD = MTH_Title;
        MethodTitle_Label.setText(TITLE_TAG.replace(TITLE_CODE, CURRENT_METHOD));
        setScreen(new MTH_Panel(MainBack_Button, XAXIS_BACKBUTTON_POSITION, YAXIS_BACKBUTTON_POSITION, MethodTitle_Label));
    }//GEN-LAST:event_MTH_ButtonActionPerformed

    private void MainBack_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainBack_ButtonActionPerformed
        MethodTitle_Label.setText(TITLE_TAG.replace(CURRENT_METHOD, TITLE_CODE));
        CURRENT_METHOD = TITLE_CODE;
        OPM_MainButtonSection.setVisible(true);
        OPM_ChooseSection.setVisible(false);
        setScreen(PantallaPrincipal);
    }//GEN-LAST:event_MainBack_ButtonActionPerformed

    private void MNR_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNR_ButtonActionPerformed
        CURRENT_METHOD = MNR_Title;
        MethodTitle_Label.setText(TITLE_TAG.replace(TITLE_CODE, CURRENT_METHOD));
        setScreen(new MNR_Panel(MainBack_Button, XAXIS_BACKBUTTON_POSITION, YAXIS_BACKBUTTON_POSITION, MethodTitle_Label));
    }//GEN-LAST:event_MNR_ButtonActionPerformed

    private void TeamTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeamTitleMouseClicked
        M.mostrarCreditos();
        updateWindow();
    }//GEN-LAST:event_TeamTitleMouseClicked

    private void TeamTitleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeamTitleMouseEntered
        Font font = TeamTitle.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        TeamTitle.setFont(font);
        //aqui todo esto no funciona, dejar el label underlined desde el principio (gui)
    }//GEN-LAST:event_TeamTitleMouseEntered

    private void MRPMC_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRPMC_ButtonActionPerformed
        CURRENT_METHOD = MRPMC_Title;
        MethodTitle_Label.setText(TITLE_TAG.replace(TITLE_CODE, CURRENT_METHOD));
        setScreen(new MRPMC_Panel(MainBack_Button, XAXIS_BACKBUTTON_POSITION, YAXIS_BACKBUTTON_POSITION, MethodTitle_Label));
    }//GEN-LAST:event_MRPMC_ButtonActionPerformed

    private void OPM_1_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPM_1_ButtonActionPerformed
        CURRENT_METHOD = OPM_Title+": "+OPM_1_Title;
        MethodTitle_Label.setText(TITLE_TAG.replace(TITLE_CODE, CURRENT_METHOD));
        setScreen(new OPM_1_Panel(MainBack_Button, XAXIS_BACKBUTTON_POSITION, YAXIS_BACKBUTTON_POSITION, MethodTitle_Label));
    }//GEN-LAST:event_OPM_1_ButtonActionPerformed

    private void OPM_2_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPM_2_ButtonActionPerformed
        CURRENT_METHOD = OPM_Title+": "+OPM_2_Title;
        MethodTitle_Label.setText(TITLE_TAG.replace(TITLE_CODE, CURRENT_METHOD));
        setScreen(new OPM_2_Panel(MainBack_Button, XAXIS_BACKBUTTON_POSITION, YAXIS_BACKBUTTON_POSITION, MethodTitle_Label));
    }//GEN-LAST:event_OPM_2_ButtonActionPerformed

    private void MNM_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNM_ButtonActionPerformed
        CURRENT_METHOD = MNM_Title;
        MethodTitle_Label.setText(TITLE_TAG.replace(TITLE_CODE, CURRENT_METHOD));
        setScreen(new MNM_Panel(MainBack_Button, XAXIS_BACKBUTTON_POSITION, YAXIS_BACKBUTTON_POSITION, MethodTitle_Label));
    }//GEN-LAST:event_MNM_ButtonActionPerformed

    private void setScreen(Component panel){
        Stage.removeAll();
        Stage.add(panel);
        Stage.revalidate();
        Stage.repaint();
        
    }
    
    private void updateWindow(){
        this.revalidate();
        this.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BacktoOPMSection_Button;
    private javax.swing.JPanel ButtonSection;
    private javax.swing.JLabel ButtonSectionTitle;
    private javax.swing.JButton MGJ_Button;
    private javax.swing.JButton MNM_Button;
    private javax.swing.JButton MNR_Button;
    private javax.swing.JButton MRPMC_Button;
    private javax.swing.JButton MTH_Button;
    private javax.swing.JButton MainBack_Button;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JLabel MethodTitle_Label;
    private javax.swing.JButton OPM_1_Button;
    private javax.swing.JButton OPM_2_Button;
    private javax.swing.JButton OPM_Button;
    private javax.swing.JPanel OPM_ChooseSection;
    private javax.swing.JPanel OPM_MainButtonSection;
    private javax.swing.JLayeredPane OPM_Section;
    private javax.swing.JPanel PantallaPrincipal;
    private javax.swing.JPanel Stage;
    private javax.swing.JLabel TeamTitle;
    private javax.swing.JPanel TopBar;
    // End of variables declaration//GEN-END:variables
}
